--- 
title       : Trying Slidify for the first time
subtitle    : Changing the style
author      : Me
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : default      # 
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
ext_widgets : {rCharts: [libraries/nvd3]}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
--- 

## Equations

$$\frac{1}{n}\sum_{i=1}^n y_i$$

--- 

## Code

```{r}
x<-(1:10)
sum(x)
```


--- 
## Slide 3

Make a list:  
* item 1  
* item 2  

Add a [link](http://slidify.org/start.html)


---

## Interactive Chart

```{r echo = FALSE, results = 'asis', message=FALSE}
require(rCharts)
haireye = as.data.frame(HairEyeColor)
n1 <- nPlot(Freq ~ Hair, group = 'Eye', type = 'multiBarChart', data = subset(haireye, Sex == 'Male'))
n1$print('chart1')
```

--- &twocol

## Two Column Layout   

*** =left
```{r echo=FALSE,message=FALSE,fig.height=6}
library(ggplot2)
data(diamonds)
diamonds<-diamonds[sample(1:nrow(diamonds),2000),]
ggplot(diamonds, aes(carat,price))+geom_point(color="cadetblue")
```


*** =right
```{r echo=FALSE,fig.height=6}
ggplot(diamonds, aes(carat, price, color=clarity))+geom_point()
```

*** =fullwidth
Going back to full width

